### ISSUE TITLE
PermissionError

### ISSUE THREAD

**Issue by 1799xy** [alokwhitewolf/Video-frame-prediction-by-multi-scale-GAN#1]
When I run the train.py, it will reports an Error: FileNotFoundError: [Errno 2] No such file or directory: 'snapshot',then if i manual create a folder called ‘snapshot’ under ‘result’，it will reports an Error: PermissionError: [Errno 13] Permission denied: 'result/snapshot'. I am a complete novice at chainer.

**Comment by alokwhitewolf** [comment]
run the command as super user maybe ? 
` sudo python3 train.py`

**Comment by 1799xy** [comment]
My operating system is win10 and I use the Administrator permission to run the program like this.  ~>_<~ 
what dose the snapshot file means？Does a snapshot.npz comes from the previous epoch and will participate in the next epoch？
![i 6f hyn52_0zhte b i6g](https://user-images.githubusercontent.com/48232767/53791819-439b2a80-3f65-11e9-91fb-713b76960cfb.png)

**Comment by alokwhitewolf** [comment]
It is mostly meant to save trainer's status so that you can resume training if you pause/quit inbetween. You may disregard it if you intend to train at a single go and not pause and resume.

**Comment by 1799xy** [comment]
I get it.  ヽ(✿ﾟ▽ﾟ)ノThank you~~~
